/**
 * Araç marka/model kataloğu.
 *
 * Hem araç girişi formundaki seçicide hem de seed verisinde kullanılır —
 * liste iki yerde ayrışmasın diye tek kaynak burasıdır.
 *
 * Kapsam kararları:
 *  - Türkiye'de sahada karşılaşılan ESKİ modeller bilerek dahil (Tofaş Şahin,
 *    Murat 124, Anadol, Daewoo Nexia, Renault Toros…). Otoparka gelen araçların
 *    önemli bir kısmı 90'lar–2000'ler modeli ve görevlinin bunları listede
 *    bulamayıp elle yazması zaman kaybettiriyor.
 *  - Hafif ticari araçlar dahil (Transit, Doblo, Kangoo…) — otoparka minibüs
 *    ve panelvan da geliyor.
 *  - Motosiklet markaları da var: otoparka motosiklet kabul ediliyorsa aynı
 *    listeden seçilebilsin diye.
 *  - Model listesi içinde sıralama alfabetik DEĞİL, aile/nesil sırasına göre
 *    (R9 → R12 → R19, 205 → 206 → 207): ilgili modeller yan yana olduğunda
 *    aranan araç daha hızlı bulunuyor.
 *
 * Listede olmayan araç için serbest metin girişi her zaman açıktır —
 * katalog asla kısıtlayıcı değildir.
 */

export type Marka = {
  ad: string;
  modeller: readonly string[];
};

export const MARKALAR: readonly Marka[] = [
  // --- Türkiye'de en yaygın markalar --------------------------------------
  {
    ad: "Tofaş",
    modeller: [
      "Murat 124",
      "Murat 131",
      "Şahin",
      "Şahin S",
      "Doğan",
      "Doğan SLX",
      "Kartal",
      "Kartal SLX",
      "Serçe",
      "Uno",
      "Tempra",
      "Tipo",
      "Palio",
      "Albea",
      "Marea",
      "Kartal Pick-Up",
    ],
  },
  {
    ad: "Renault",
    modeller: [
      "Toros",
      "R9",
      "R11",
      "R12",
      "R19",
      "R21",
      "R25",
      "Broadway",
      "Twingo",
      "Clio",
      "Clio Symbol",
      "Symbol",
      "Thalia",
      "Megane",
      "Megane Sedan",
      "Fluence",
      "Laguna",
      "Latitude",
      "Safrane",
      "Scenic",
      "Grand Scenic",
      "Espace",
      "Kangoo",
      "Trafic",
      "Master",
      "Taliant",
      "Captur",
      "Kadjar",
      "Koleos",
      "Austral",
      "Arkana",
      "Duster",
      "Zoe",
      "Talisman",
      "Express",
    ],
  },
  {
    ad: "Fiat",
    modeller: [
      "126",
      "127",
      "131",
      "Uno",
      "Tempra",
      "Tipo",
      "Marea",
      "Palio",
      "Palio Weekend",
      "Albea",
      "Siena",
      "Linea",
      "Punto",
      "Grande Punto",
      "Bravo",
      "Brava",
      "Croma",
      "Panda",
      "Egea",
      "Egea Cross",
      "Doblo",
      "Fiorino",
      "Ducato",
      "Scudo",
      "Multipla",
      "Idea",
      "Sedici",
      "Freemont",
      "500",
      "500L",
      "500X",
      "Talento",
    ],
  },
  {
    ad: "Volkswagen",
    modeller: [
      "Beetle",
      "Golf",
      "Polo",
      "Passat",
      "Passat Variant",
      "Jetta",
      "Bora",
      "Vento",
      "Corrado",
      "Scirocco",
      "Arteon",
      "CC",
      "Up",
      "Lupo",
      "Fox",
      "Touran",
      "Sharan",
      "Caddy",
      "Transporter",
      "Caravelle",
      "Multivan",
      "Crafter",
      "LT",
      "Tiguan",
      "Touareg",
      "T-Roc",
      "T-Cross",
      "Taigo",
      "Amarok",
      "ID.3",
      "ID.4",
    ],
  },
  {
    ad: "Ford",
    modeller: [
      "Taunus",
      "Escort",
      "Sierra",
      "Orion",
      "Ka",
      "Fiesta",
      "Focus",
      "Focus C-Max",
      "Mondeo",
      "Cougar",
      "Puma",
      "Fusion",
      "B-Max",
      "C-Max",
      "S-Max",
      "Galaxy",
      "Kuga",
      "EcoSport",
      "Edge",
      "Explorer",
      "Mustang",
      "Ranger",
      "Transit",
      "Transit Custom",
      "Transit Courier",
      "Transit Connect",
      "Tourneo",
      "Tourneo Custom",
      "Tourneo Courier",
      "Tourneo Connect",
      "Cargo",
      "Otosan Kamyonet",
    ],
  },
  {
    ad: "Opel",
    modeller: [
      "Kadett",
      "Ascona",
      "Rekord",
      "Omega",
      "Vectra",
      "Astra",
      "Astra Sedan",
      "Corsa",
      "Tigra",
      "Calibra",
      "Signum",
      "Insignia",
      "Agila",
      "Meriva",
      "Zafira",
      "Antara",
      "Frontera",
      "Mokka",
      "Mokka X",
      "Crossland",
      "Grandland",
      "Combo",
      "Vivaro",
      "Movano",
      "Adam",
      "Karl",
    ],
  },
  {
    ad: "Toyota",
    modeller: [
      "Starlet",
      "Corona",
      "Carina",
      "Corolla",
      "Corolla Verso",
      "Corolla Cross",
      "Auris",
      "Avensis",
      "Camry",
      "Yaris",
      "Yaris Cross",
      "Aygo",
      "Verso",
      "Prius",
      "C-HR",
      "RAV4",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Hilux",
      "Highlander",
      "Proace",
      "Proace City",
      "Supra",
      "Celica",
      "MR2",
      "bZ4X",
      "Hiace",
    ],
  },
  {
    ad: "Honda",
    modeller: [
      "Civic",
      "Civic Sedan",
      "Accord",
      "City",
      "Jazz",
      "Prelude",
      "Legend",
      "Integra",
      "CR-V",
      "HR-V",
      "ZR-V",
      "Insight",
      "e:Ny1",
      "Stream",
      "FR-V",
      // Motosiklet
      "PCX",
      "Forza",
      "CBR",
      "CB",
      "NC750X",
      "Africa Twin",
      "Dio",
      "Activa",
    ],
  },
  {
    ad: "Hyundai",
    modeller: [
      "Pony",
      "Excel",
      "Accent",
      "Accent Era",
      "Accent Blue",
      "Accent Admire",
      "Getz",
      "Elantra",
      "Sonata",
      "Coupe",
      "Matrix",
      "i10",
      "i20",
      "i20 Active",
      "i30",
      "i40",
      "ix20",
      "ix35",
      "Tucson",
      "Santa Fe",
      "Kona",
      "Bayon",
      "Ioniq",
      "Ioniq 5",
      "H100",
      "H1",
      "Starex",
      "Staria",
      "Terracan",
    ],
  },
  {
    ad: "Peugeot",
    modeller: [
      "104",
      "106",
      "205",
      "206",
      "207",
      "208",
      "301",
      "306",
      "307",
      "308",
      "309",
      "405",
      "406",
      "407",
      "408",
      "504",
      "505",
      "508",
      "605",
      "607",
      "1007",
      "2008",
      "3008",
      "4008",
      "5008",
      "806",
      "807",
      "RCZ",
      "Bipper",
      "Partner",
      "Rifter",
      "Expert",
      "Boxer",
      "Traveller",
      "J5",
    ],
  },
  {
    ad: "Citroën",
    modeller: [
      "2CV",
      "AX",
      "BX",
      "ZX",
      "Saxo",
      "Xsara",
      "Xsara Picasso",
      "Xantia",
      "XM",
      "C1",
      "C2",
      "C3",
      "C3 Picasso",
      "C3 Aircross",
      "C4",
      "C4 Cactus",
      "C4 Picasso",
      "C5",
      "C5 Aircross",
      "C6",
      "C-Elysée",
      "Berlingo",
      "Nemo",
      "Jumpy",
      "Jumper",
      "SpaceTourer",
    ],
  },
  {
    ad: "Mercedes-Benz",
    modeller: [
      "190",
      "200",
      "230",
      "250",
      "280",
      "300",
      "A Serisi",
      "B Serisi",
      "C Serisi",
      "CLA",
      "CLK",
      "CLS",
      "E Serisi",
      "S Serisi",
      "SLK",
      "SL",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "ML",
      "GL",
      "G Serisi",
      "V Serisi",
      "Vito",
      "Viano",
      "Vaneo",
      "Citan",
      "Sprinter",
      "Vario",
      "EQA",
      "EQC",
      "Atego",
      "Axor",
      "Actros",
      "Travego",
    ],
  },
  {
    ad: "BMW",
    modeller: [
      "1 Serisi",
      "2 Serisi",
      "3 Serisi",
      "4 Serisi",
      "5 Serisi",
      "6 Serisi",
      "7 Serisi",
      "8 Serisi",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z3",
      "Z4",
      "i3",
      "i4",
      "iX",
      "M2",
      "M3",
      "M4",
      "M5",
    ],
  },
  {
    ad: "Audi",
    modeller: [
      "80",
      "100",
      "A1",
      "A3",
      "A4",
      "A4 Avant",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "e-tron",
      "S3",
      "S4",
      "RS3",
      "RS6",
    ],
  },

  // --- Yaygın diğer markalar ----------------------------------------------
  {
    ad: "Dacia",
    modeller: [
      "1310",
      "Nova",
      "Solenza",
      "Logan",
      "Logan MCV",
      "Sandero",
      "Sandero Stepway",
      "Duster",
      "Dokker",
      "Lodgy",
      "Jogger",
      "Spring",
      "Pick-Up",
    ],
  },
  {
    ad: "Skoda",
    modeller: [
      "Favorit",
      "Felicia",
      "Octavia",
      "Octavia Combi",
      "Fabia",
      "Rapid",
      "Superb",
      "Roomster",
      "Praktik",
      "Yeti",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Scala",
      "Enyaq",
      "Citigo",
      "105",
      "120",
      "130",
      "Forman",
    ],
  },
  {
    ad: "Seat",
    modeller: [
      "Marbella",
      "Malaga",
      "Ibiza",
      "Cordoba",
      "Toledo",
      "Leon",
      "Altea",
      "Exeo",
      "Alhambra",
      "Arosa",
      "Mii",
      "Arona",
      "Ateca",
      "Tarraco",
      "Inca",
    ],
  },
  {
    ad: "Nissan",
    modeller: [
      "Sunny",
      "Bluebird",
      "Primera",
      "Almera",
      "Micra",
      "Note",
      "Pulsar",
      "Maxima",
      "Qashqai",
      "Juke",
      "Kicks",
      "X-Trail",
      "Murano",
      "Pathfinder",
      "Terrano",
      "Patrol",
      "Navara",
      "Leaf",
      "NV200",
      "Primastar",
      "Interstar",
      "Cabstar",
    ],
  },
  {
    ad: "Kia",
    modeller: [
      "Pride",
      "Sephia",
      "Shuma",
      "Rio",
      "Cerato",
      "Ceed",
      "ProCeed",
      "Optima",
      "K5",
      "Picanto",
      "Venga",
      "Carens",
      "Carnival",
      "Sportage",
      "Sorento",
      "Soul",
      "Stonic",
      "Niro",
      "EV6",
      "Bongo",
      "Besta",
      "Pregio",
    ],
  },
  {
    ad: "Mazda",
    modeller: [
      "121",
      "323",
      "323F",
      "626",
      "929",
      "2",
      "3",
      "5",
      "6",
      "MX-5",
      "RX-8",
      "Premacy",
      "Tribute",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "BT-50",
      "E2200",
    ],
  },
  {
    ad: "Suzuki",
    modeller: [
      "Alto",
      "Swift",
      "Baleno",
      "Liana",
      "SX4",
      "SX4 S-Cross",
      "Vitara",
      "Grand Vitara",
      "Jimny",
      "Ignis",
      "Samurai",
      "Celerio",
      // Motosiklet
      "Burgman",
      "GSX",
      "V-Strom",
      "Address",
    ],
  },
  {
    ad: "Mitsubishi",
    modeller: [
      "Colt",
      "Lancer",
      "Lancer Evolution",
      "Galant",
      "Carisma",
      "Space Star",
      "Space Wagon",
      "ASX",
      "Outlander",
      "Eclipse Cross",
      "Pajero",
      "L200",
      "L300",
      "Canter",
    ],
  },
  {
    ad: "Chevrolet",
    modeller: [
      "Spark",
      "Kalos",
      "Aveo",
      "Lacetti",
      "Nubira",
      "Cruze",
      "Epica",
      "Evanda",
      "Rezzo",
      "Tacuma",
      "Captiva",
      "Trax",
      "Orlando",
      "Camaro",
      "Blazer",
    ],
  },
  {
    ad: "Daewoo",
    modeller: [
      "Tico",
      "Matiz",
      "Nexia",
      "Cielo",
      "Espero",
      "Lanos",
      "Nubira",
      "Leganza",
      "Kalos",
      "Racer",
    ],
  },
  {
    ad: "Volvo",
    modeller: [
      "240",
      "340",
      "440",
      "460",
      "850",
      "940",
      "960",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
      "FH",
      "FM",
    ],
  },
  {
    ad: "Alfa Romeo",
    modeller: [
      "33",
      "145",
      "146",
      "147",
      "155",
      "156",
      "159",
      "164",
      "166",
      "Giulietta",
      "Giulia",
      "MiTo",
      "Brera",
      "Stelvio",
      "Tonale",
    ],
  },
  {
    ad: "SsangYong",
    modeller: ["Korando", "Musso", "Rexton", "Actyon", "Kyron", "Tivoli", "Rodius"],
  },
  {
    ad: "Jeep",
    modeller: [
      "Cherokee",
      "Grand Cherokee",
      "Compass",
      "Renegade",
      "Wrangler",
      "Patriot",
      "Avenger",
    ],
  },
  {
    ad: "Land Rover",
    modeller: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Evoque",
      "Range Rover Velar",
    ],
  },
  {
    ad: "Mini",
    modeller: ["Cooper", "Cooper S", "One", "Clubman", "Countryman", "Paceman"],
  },
  {
    ad: "Lexus",
    modeller: ["IS", "ES", "GS", "LS", "CT", "UX", "NX", "RX", "LX"],
  },
  {
    ad: "Porsche",
    modeller: ["911", "Boxster", "Cayman", "Panamera", "Cayenne", "Macan", "Taycan"],
  },
  {
    ad: "Smart",
    modeller: ["Fortwo", "Forfour", "Roadster"],
  },
  {
    ad: "Cupra",
    modeller: ["Leon", "Formentor", "Ateca", "Born", "Terramar"],
  },
  {
    ad: "MG",
    modeller: ["MG3", "MG4", "MG5", "ZS", "HS", "Marvel R", "ZR", "ZT"],
  },
  {
    ad: "Chery",
    modeller: ["QQ", "Kimo", "Alia", "Tiggo", "Tiggo 7", "Tiggo 8", "Omoda 5"],
  },
  {
    ad: "BYD",
    modeller: ["Atto 3", "Seal", "Dolphin", "Han", "Tang", "Song", "Seal U"],
  },
  {
    ad: "Togg",
    modeller: ["T10X", "T10F"],
  },
  {
    ad: "Tesla",
    modeller: ["Model 3", "Model Y", "Model S", "Model X"],
  },
  {
    ad: "Lada",
    modeller: [
      "2101",
      "2105",
      "2106",
      "2107",
      "Samara",
      "Niva",
      "Vega",
      "Kalina",
      "Priora",
      "Granta",
      "Vesta",
      "Largus",
    ],
  },
  {
    ad: "Anadol",
    modeller: ["A1", "A2", "A8-16", "SV-1600", "STC-16", "Böcek", "Pikap"],
  },
  {
    ad: "Daihatsu",
    modeller: ["Charade", "Sirion", "Terios", "Cuore", "Materia", "Hijet"],
  },
  {
    ad: "Subaru",
    modeller: ["Impreza", "Legacy", "Forester", "Outback", "XV", "BRZ", "Justy"],
  },
  {
    ad: "Rover",
    modeller: ["200", "400", "600", "800", "25", "45", "75", "Streetwise"],
  },
  {
    ad: "Lancia",
    modeller: ["Delta", "Kappa", "Lybra", "Thesis", "Ypsilon", "Musa", "Phedra"],
  },
  {
    ad: "Jaguar",
    modeller: ["X-Type", "S-Type", "XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace"],
  },
  {
    ad: "Infiniti",
    modeller: ["Q30", "Q50", "Q70", "QX30", "QX50", "QX70"],
  },
  {
    ad: "Proton",
    modeller: ["Wira", "Persona", "Satria", "Savvy", "Gen-2", "Waja"],
  },
  {
    ad: "Tata",
    modeller: ["Telcoline", "Indica", "Indigo", "Xenon", "Safari"],
  },
  {
    ad: "Geely",
    modeller: ["Emgrand", "Coolray", "Tugella", "Atlas"],
  },

  // --- Ticari araç ve otobüs ----------------------------------------------
  {
    ad: "Isuzu",
    modeller: [
      "Trooper",
      "Rodeo",
      "D-Max",
      "Panther",
      "Turkuaz",
      "Roybus",
      "Novolux",
      "NPR",
      "NQR",
      "Citiport",
      "Midi",
    ],
  },
  {
    ad: "Iveco",
    modeller: [
      "Daily",
      "Turbo Daily",
      "Eurocargo",
      "Stralis",
      "Trakker",
      "Massif",
      "Otoyol",
    ],
  },
  {
    ad: "Karsan",
    modeller: ["Jest", "Jest Electric", "Atak", "Star", "J10", "Peugeot J9"],
  },
  {
    ad: "Otokar",
    modeller: ["Sultan", "Navigo", "Vectio", "Kent", "Doruk", "M2010", "Atlas"],
  },
  {
    ad: "BMC",
    modeller: ["Levend", "Fatih", "Pro", "Belde", "Profesyonel", "Megastar", "TGR"],
  },
  {
    ad: "Temsa",
    modeller: ["Safir", "Maraton", "Prestij", "Tourmalin", "MD9", "Avenue"],
  },
  {
    ad: "MAN",
    modeller: ["TGX", "TGS", "TGM", "TGL", "Lion's Coach", "F2000"],
  },
  {
    ad: "Scania",
    modeller: ["R Serisi", "S Serisi", "G Serisi", "P Serisi", "Touring"],
  },
  {
    ad: "DAF",
    modeller: ["XF", "CF", "LF", "XG"],
  },
  {
    ad: "Renault Trucks",
    modeller: ["Premium", "Magnum", "Midlum", "T Serisi", "D Serisi", "Kerax"],
  },

  // --- Motosiklet markaları -----------------------------------------------
  // Otoparka motosiklet de geliyor. Honda ve Suzuki hem otomobil hem motosiklet
  // ürettiği için modelleri kendi marka listelerine eklendi; yalnızca motosiklet
  // üreten markalar aşağıda ayrı duruyor.
  {
    ad: "Yamaha",
    modeller: [
      "NMAX",
      "XMAX",
      "TMAX",
      "MT-03",
      "MT-07",
      "MT-09",
      "R25",
      "R7",
      "Tracer",
      "Crypton",
      "Jog",
      "Aerox",
    ],
  },
  {
    ad: "Kawasaki",
    modeller: ["Ninja", "Z650", "Z900", "Versys", "Vulcan", "W800", "KLX"],
  },
  {
    ad: "Vespa",
    modeller: ["Primavera", "Sprint", "GTS", "LX", "PX"],
  },
  {
    ad: "Piaggio",
    modeller: ["Liberty", "Beverly", "Medley", "MP3", "Zip", "Ape"],
  },
  {
    ad: "Bajaj",
    modeller: ["Pulsar", "Boxer", "Dominar", "Discover", "Avenger"],
  },
  {
    ad: "Kuba",
    modeller: ["Vertus", "Mirage", "CR", "Wolf", "Firebird"],
  },
  {
    ad: "Mondial",
    modeller: ["Drift", "Turkuaz", "Znt", "Fst", "Hpc", "Revival"],
  },
  {
    ad: "RKS",
    modeller: ["Fever", "Titanic", "Speedy", "Vetro", "Skywing"],
  },
  {
    ad: "Arora",
    modeller: ["AR", "Cappuccino", "Estet", "Kanuni"],
  },
  {
    ad: "Kanuni",
    modeller: ["Kanuni 125", "Mizu", "Sportstar"],
  },
  {
    ad: "SYM",
    modeller: ["Symphony", "Jet", "Fiddle", "Joymax", "Maxsym"],
  },
  {
    ad: "Kymco",
    modeller: ["Agility", "People", "Downtown", "Like", "X-Town"],
  },
  {
    ad: "TVS",
    modeller: ["Apache", "Ntorq", "Jupiter", "Neo"],
  },

  // Katalogda olmayan araçlar için — model serbest metin olarak yazılır.
  {
    ad: "Diğer",
    modeller: [],
  },
];

/** Katalogdaki tüm marka adları (seçici için). */
export const MARKA_ADLARI: readonly string[] = MARKALAR.map((m) => m.ad);

/** Bir markanın modelleri; marka bulunamazsa boş dizi. */
export function markaModelleri(marka: string): readonly string[] {
  return MARKALAR.find((m) => m.ad.toLowerCase() === marka.trim().toLowerCase())?.modeller ?? [];
}

/** Katalogda gerçekten model tanımlı mı? ("Diğer" gibi boş markalar için false) */
export function markaModelliMi(marka: string): boolean {
  return markaModelleri(marka).length > 0;
}
